server:
  port: 8081
  servlet:
    context-path: /post

spring:
  application:
    name: postagem
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest

postagem:
  rabbitmq:
    exchange: postagem.exchange
    routingkey: postagem.routingkey